### ISSUE TITLE
add binary for latest version and/or provide build instructions

### ISSUE THREAD

**Issue by olets** [nolaneo/SeaEye#25]
I don't use Xcode much, and after some searching I'm still unclear about how to export a standalone .app. (I'm currently running the "export for testing" copy, despite the "this is unsigned and can be modified without your knowing" warning)

Would be great to have a downloadable binary for 0.5

**Comment by nolaneo** [comment]
👍

@Mongey we should look at getting your latest updates into master and push out a 0.6.

**Comment by stackptr** [comment]
Looks like this still needs to be done? `README.md` still has a binary for 0.4 for download

**Comment by stackptr** [comment]
More confusingly, the version in `.xcodeproj` on the latest `master` still says version 0.4?

**Comment by olets** [comment]
bump :) would be cool to get to use the latest work. I'm up for compiling from source if we could add instructions, but a release is the dream

**Comment by nolaneo** [comment]
@Mongey want to pull in your updates and do a 0.6?
Maybe also get this one in too? https://github.com/nolaneo/SeaEye/pull/31

**Comment by Mongey** [comment]
@nolaneo I've merged #31. I've got one or two more PRs I'd like to get in, then I'll do a **0.5** release. (0.4 is the last release and master is now 0.5-dev).
Spoiler: it's a PR to get the latest release from GitHub Releases rather than [the file that says we're on 0.3](https://github.com/nolaneo/SeaEye/blob/master/project_status.json#L2)
